<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LM-SJC-11018021" failures="1" tests="1" name="Test" time="1.396" errors="0" timestamp="23 Nov 2019 05:35:02 GMT">
  <testcase classname="test.testAPI.testAPI1stCases" name="testcase1St" time="1.381">
    <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [4]
at test.testAPI.testAPI1stCases.testcase1St(testAPI1stCases.java:26)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testcase1St -->
</testsuite> <!-- Test -->
